<!-- MHonArc v2.1.0 -->
<!--X-Subject: [pgsql&#45;jp: 27560] pg_connectの呼び出し失敗について -->
<!--X-From: "saito" <saito@hitachi&#45;mi.co.jp> -->
<!--X-Date: Mon, 7 Oct 2002 14:53:27 +0900 -->
<!--X-Message-Id: 004401c26dc5$db67c0f0$47d3a8c0@mi.hitachimc.co.jp -->
<!--X-ContentType: text/plain -->
<!--X-Head-End-->
<HTML>
<HEAD>
<TITLE>[pgsql-jp: 27560] pg_connectの呼び出し失敗について </TITLE>
<LINK REV="made" HREF="mailto:saito@hitachi-mi.co.jp">
</HEAD>
<BODY BGCOLOR="#ffffff">
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<HR>
[<A HREF="msg00061.html">Date Prev</A>][<A HREF="msg00063.html">Date Next</A>][<A HREF="msg00101.html">Thread Prev</A>][<A HREF="msg00063.html">Thread Next</A>][<A HREF="index.html#00062">Date Index</A>][<A HREF="threads.html#00062">Thread Index</A>]
<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<H1>[pgsql-jp: 27560] pg_connectの呼び出し失敗について</H1>
<HR>
<!--X-Subject-Header-End-->
<UL>
<LI><em>From</em>: "saito" &lt;<A HREF="mailto:saito@hitachi-mi.co.jp">saito@hitachi-mi.co.jp</A>&gt;</LI>
<LI><em>Date</em>: Mon, 7 Oct 2002 14:53:27 +0900</LI>
<LI><em>Delivered-To</em>: pgsql-jp@ml.postgresql.jp</LI>
<LI><em>List-Archive</em>: &lt;http://ml.postgresql.jp/pipermail/pgsql-jp/&gt;</LI>
<LI><em>List-Help</em>: &lt;mailto:pgsql-jp-request@ml.postgresql.jp?subject=help&gt;</LI>
<LI><em>List-Id</em>: PostgreSQL Japanese Mailing List &lt;pgsql-jp.ml.postgresql.jp&gt;</LI>
<LI><em>List-Post</em>: &lt;mailto:pgsql-jp@ml.postgresql.jp&gt;</LI>
<LI><em>List-Subscribe</em>: &lt;http://ml.postgresql.jp/mailman/listinfo/pgsql-jp&gt;,&lt;mailto:pgsql-jp-request@ml.postgresql.jp?subject=subscribe&gt;</LI>
<LI><em>List-Unsubscribe</em>: &lt;http://ml.postgresql.jp/mailman/listinfo/pgsql-jp&gt;,&lt;mailto:pgsql-jp-request@ml.postgresql.jp?subject=unsubscribe&gt;</LI>
</UL>
<!--X-Head-Body-Sep-Begin-->
<HR>
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<PRE>
はじめまして、saitoと申します。

postgreSQLへ接続しようとしたところ、
pg_connect呼び出し時、以下のエラーで接続に失敗してしまいます。

呼び出し方法：
$conn = pg_Connect("dbname=HMC user=hmcadmin");
エラーメッセージ：
Warning: Unable to connect to PostgreSQL server:
FATAL 1: IDENT authentication failed for user "hmcadmin" ・・・・

dbはinitdbにて”HMC”を既に作成済みです。
また、userもcreateuserにて”hmcadmin”を作成済みです。

備考：
テストサーバにて動作確認を行った際はうまく動作したのですが、
本番サーバに移行したところ、上記の現象が発生してしまいました。
なにか原因があるのでしょうか？
※テストサーバも本番サーバも同じredhat linux7.3で、
    PHP、PostgreSQLも同様のバージョンを使用しており、同じ手順でふんだつもり
ですが・・・

どなたか原因をご存知のかた、ご教授お願い致します。


</PRE>

<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
<HR>
<UL><LI><STRONG>Follow-Ups</STRONG>:
<UL>
<LI><STRONG><A NAME="00067" HREF="msg00067.html">[pgsql-jp: 27565] Re: pg_connectの呼び出し失敗について</A></STRONG>
<UL><LI><EM>From:</EM> Kazumasa Gotoh &lt;kgotoh@cic-kk.co.jp&gt;</LI></UL></LI>
<LI><STRONG><A NAME="00066" HREF="msg00066.html">[pgsql-jp: 27564] Re: pg_connectの呼び出し失敗について</A></STRONG>
<UL><LI><EM>From:</EM> Takao Kato &lt;sirius@jp.fujitsu.com&gt;</LI></UL></LI>
<LI><STRONG><A NAME="00063" HREF="msg00063.html">[pgsql-jp: 27561] Re: pg_connectの呼び出し失敗について</A></STRONG>
<UL><LI><EM>From:</EM> matsuda &lt;yumatuda@msoft.co.jp&gt;</LI></UL></LI>
</UL></LI></UL>
<!--X-Follow-Ups-End-->
<!--X-References-->
<!--X-References-End-->
<!--X-BotPNI-->
<UL>
<LI>Prev by Date:
<STRONG><A HREF="msg00061.html">[pgsql-jp: 27559] Re: postgres のバージョンアップ</A></STRONG>
</LI>
<LI>Next by Date:
<STRONG><A HREF="msg00063.html">[pgsql-jp: 27561] Re: pg_connectの呼び出し失敗について</A></STRONG>
</LI>
<LI>Prev by thread:
<STRONG><A HREF="msg00101.html">[pgsql-jp: 27599] Re: pg_ctl とOS 起動時のpassword  要求について</A></STRONG>
</LI>
<LI>Next by thread:
<STRONG><A HREF="msg00063.html">[pgsql-jp: 27561] Re: pg_connectの呼び出し失敗について</A></STRONG>
</LI>
<LI>Index(es):
<UL>
<LI><A HREF="index.html#00062"><STRONG>Date</STRONG></A></LI>
<LI><A HREF="threads.html#00062"><STRONG>Thread</STRONG></A></LI>
</UL>
</LI>
</UL>

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
</BODY>
</HTML>
