<!-- MHonArc v2.1.0 -->
<!--X-Subject: [pgsql&#45;jp 19614] Re: Update のエラー -->
<!--X-From: Ryota Imaoka <imaoka@rastaway.com> -->
<!--X-Date: Mon, 22 Jan 2001 20:12:09 +0900 -->
<!--X-Message-Id: 3A6C1577.AC272660@rastaway.com -->
<!--X-ContentType: text/plain -->
<!--X-Reference-Id: 3A666E82.4DB04AE9@rastaway.com -->
<!--X-Reference-Id: 3A66BFA5.B80209C0@rastaway.com -->
<!--X-Head-End-->
<HTML>
<HEAD>
<TITLE>[pgsql-jp 19614] Re: Update のエラー </TITLE>
<LINK REV="made" HREF="mailto:imaoka@rastaway.com">
</HEAD>
<BODY BGCOLOR="#ffffff">
<!--X-Body-Begin-->
<!--X-User-Header-->
<!--X-User-Header-End-->
<!--X-TopPNI-->
<HR>
[<A HREF="msg00306.html">Date Prev</A>][<A HREF="msg00308.html">Date Next</A>][<A HREF="msg00261.html">Thread Prev</A>][<A HREF="msg00323.html">Thread Next</A>][<A HREF="index.html#00307">Date Index</A>][<A HREF="threads.html#00307">Thread Index</A>]
<!--X-TopPNI-End-->
<!--X-MsgBody-->
<!--X-Subject-Header-Begin-->
<H1>[pgsql-jp 19614] Re: Update のエラー</H1>
<HR>
<!--X-Subject-Header-End-->
<UL>
<LI><em>From</em>: Ryota Imaoka &lt;<A HREF="mailto:imaoka@rastaway.com">imaoka@rastaway.com</A>&gt;</LI>
<LI><em>Date</em>: Mon, 22 Jan 2001 20:12:09 +0900</LI>
<LI><em>References</em>: &lt;<A HREF="msg00238.html">3A666E82.4DB04AE9@rastaway.com</A>&gt; &lt;<A HREF="msg00261.html">3A66BFA5.B80209C0@rastaway.com</A>&gt;</LI>
</UL>
<!--X-Head-Body-Sep-Begin-->
<HR>
<!--X-Head-Body-Sep-End-->
<!--X-Body-of-Message-->
<PRE>
自己レスですが、
<A HREF="http://postgresql.readysetnet.com/mhonarc/pgsql-admin/1998-08/msg00048.html">http://postgresql.readysetnet.com/mhonarc/pgsql-admin/1998-08/msg00048.html</A>
に同じ症状に関する報告が書いていました。

どうやらtriggerが問題らしいので、（このテーブルにも２つのtriggerを使っていま
した）
一度triggerをdropして、再度create triggerすると問題解消しました。


&gt; &gt; 今まで正常に機能していたテーブルが、突然Updateでエラーが出るようになりま
&gt; &gt; した。
&gt; &gt; （select,delete,insertは問題ありません。）
&gt; &gt;
&gt; &gt; psqlからそのテーブルに対してUpdateをかけると、
&gt; &gt;
&gt; &gt; ERROR:  fmgr_info: function 231320: cache lookup failed
&gt; &gt;
&gt; &gt; というメッセージがでて更新できません。
&gt; &gt; また、dump時もエラーが発生します。
&gt; &gt;
&gt; &gt; $ pg_dump database &gt; database.out
&gt; &gt; PQgetvalue: ERROR! tuple number 0 is out of range 0..-1
&gt; &gt; Segmentation fault (core dumped)
&gt; &gt;
&gt; &gt; これらは、いったいどのような問題なのでしょうか？
&gt; &gt; また、どうすれば復旧できるのでしょうか？
&gt; &gt; 御存じの方がいたら教えて下さい。
&gt; &gt; よろしくお願いします。
&gt; &gt;
&gt; &gt; [環境]
&gt; &gt;                             version
&gt; &gt; ---------------------------------------------------------------
&gt; &gt;  PostgreSQL 7.0.2 on i686-pc-linux-gnu, compiled by gcc 2.95.2
</PRE>

<!--X-Body-of-Message-End-->
<!--X-MsgBody-End-->
<!--X-Follow-Ups-->
<HR>
<UL><LI><STRONG>Follow-Ups</STRONG>:
<UL>
<LI><STRONG><A NAME="00323" HREF="msg00323.html">[pgsql-jp 19630] Re: Update のエラー</A></STRONG>
<UL><LI><EM>From:</EM> "INTERNET platz" &lt;platz@mx51.tiki.ne.jp&gt;</LI></UL></LI>
</UL></LI></UL>
<!--X-Follow-Ups-End-->
<!--X-References-->
<UL><LI><STRONG>References</STRONG>:
<UL>
<LI><STRONG><A NAME="00238" HREF="msg00238.html">[pgsql-jp 19545] Update のエラー</A></STRONG>
<UL><LI><EM>From:</EM> Ryota Imaoka &lt;imaoka@rastaway.com&gt;</LI></UL></LI>
<LI><STRONG><A NAME="00261" HREF="msg00261.html">[pgsql-jp 19568] Re: Update のエラー</A></STRONG>
<UL><LI><EM>From:</EM> Ryota Imaoka &lt;imaoka@rastaway.com&gt;</LI></UL></LI>
</UL></LI></UL>
<!--X-References-End-->
<!--X-BotPNI-->
<UL>
<LI>Prev by Date:
<STRONG><A HREF="msg00306.html">[pgsql-jp 19613] Re: PGSQL の高速化</A></STRONG>
</LI>
<LI>Next by Date:
<STRONG><A HREF="msg00308.html">[pgsql-jp 19615] SQL 　本</A></STRONG>
</LI>
<LI>Prev by thread:
<STRONG><A HREF="msg00261.html">[pgsql-jp 19568] Re: Update のエラー</A></STRONG>
</LI>
<LI>Next by thread:
<STRONG><A HREF="msg00323.html">[pgsql-jp 19630] Re: Update のエラー</A></STRONG>
</LI>
<LI>Index(es):
<UL>
<LI><A HREF="index.html#00307"><STRONG>Date</STRONG></A></LI>
<LI><A HREF="threads.html#00307"><STRONG>Thread</STRONG></A></LI>
</UL>
</LI>
</UL>

<!--X-BotPNI-End-->
<!--X-User-Footer-->
<!--X-User-Footer-End-->
</BODY>
</HTML>
